services:
  - type: web
    name: andesbike-frontend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
